### PR TITLE
fix: add initramfs modules

### LINKED ISSUE #25: Feature Request: Add Surface Aggregator to initramfs
If a user configures their install with Full Disk Encryption on a device using the Surface Aggregator Module, they are unable to enter their passkey with the built in keyboard with the default Silverblue initramfs. After reading [linux-surface: Disk Encryption](https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption) I was able to resolve this by writing the following to `/etc/dracut.conf.d/surface.conf` and running `rpm-ostree initramfs --enable`:

```conf
add_drivers+="surface_hid_core surface_hid surface_aggregator_registry surface_aggregator surface_aggregator_hub pinctrl_amd"
```

I don't know if this configuration is possible in the image generation process, but if it is it would make the process of bringing up a Silverblue/uBlue install on a Surface using the SAM (like my Surface Laptop 3 AMD) much easier.

### PR DESCRIPTION
**Pull request by castrojo**
Fixes #25

### CODE REVIEW

**Comment by fiftydinar** [comment]
I can't PR my changes here for some reason, so I will spit it here:

delete modprobe.d & ublue-surface.conf

use modules-load.d instead

In ublue-surface.conf, put this:

```
# Add modules necessary for Disk Encryption via keyboard
surface_aggregator
surface_aggregator_registry
surface_aggregator_hub
surface_hid_core

# Surface Laptop 3/Surface Book 3 and later
surface_hid
surface_kbd

# Only on AMD models
pinctrl_amd

# Only on Intel models
intel_lpss
intel_lpss_pci

# For Surface Laptop 3/Surface Book 3
pinctrl_icelake

# For Surface Laptop 4/Surface Laptop Studio
pinctrl_tigerlake
```

I added every driver from the surface list needed for all Surface hardware.

Module, which is not needed for some configurations, like pinctrl_amd for Intel Surface, won't load anyway, as that driver is not available on that system.

This also needs an edit in surface setup:

`SURFACE_INITRAMFS+=("/etc/modprobe.d/ublue-surface.conf")`

to

`SURFACE_INITRAMFS+=("/etc/modules-load.d/ublue-surface.conf")`

**Comment by castrojo** [comment]
OK got those in there, thanks!

**Comment by fiftydinar** [comment]
> OK got those in there, thanks!

You forgot to delete modprobe.d folder & put ublue-surface.conf in modules-load.d folder

**Comment by fiftydinar** [comment]
All good, I approve

**Review by bketelsen — APPROVED** [review]

**Comment by fiftydinar** [comment]
I forgot to add:
8250_dw

in ublue-surface.conf

```
# Add modules necessary for Disk Encryption via keyboard
surface_aggregator
surface_aggregator_registry
surface_aggregator_hub
surface_hid_core
8250_dw
```
My bad.
Better to fix it now than later.

I will file an separate PR to fix this.

**Pull request merged**
